name: Bug Report
description: Submit a new bug report
body:
  - type: markdown
    attributes:
      value: "Before reporting a bug here, please make sure you're running the latest, stable version of Curepur."

  - type: input
    attributes:
      label: "Spark link"
      description: "Please share your Spark profilings through a link, not a screenshot! Screenshots inhibit our ability to figure out the real cause of the issue."
      placeholder: "Output of command `/spark profiler --timeout 300`"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behaviour"
      description: "What you expected to see."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Observed/Actual behaviour"
      description: "What you actually saw."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Curepur version"
      description: |
        Run command `/version` on your servers console and **paste** the full, unmodified output here.
        "latest" is *not* a version; we require the output of `/version` to adequately track down the issue.
        Additionally, do **NOT provide a screenshot**, you **MUST paste the entire output**!
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: "Agreements"
      options:
        - label: "I'm running the latest, stable version of Curepur available from https://uroria.com/curepur/downloads"
          required: true
        - label: "I have searched for and ensured there isn't already an open issue regarding this."
          required: true
        - label: "I ticked all the boxes without actually reading them."
          required: false
        - label: "My Client version of Minecraft is supported by Curepur."
          required: true

  - type: textarea
    attributes:
      label: "Other"
      description: |
        Please include other helpful information below.
        The more information we receive, the quicker and more effective we can be at finding the solution to the issue.
        *And yes, you can include screenshots here.**
    validations:
      required: false