name: Publish Latest

on:
  push:
    branches: [ latest ]

jobs:
  portal:
    name: Publish to Maven Central
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      PROJECT_CHANNEL: "latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set outputs
        id: vars
        run: |
          echo "short_commit_hash=${GITHUB_SHA::10}" >> $GITHUB_OUTPUT

      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace
        
      - name: Publish
        env:
          PROJECT_VERSION: ${{ steps.vars.outputs.short_commit_hash }}
        run: |
          ./gradlew :curepur-api:publishToCentralPortal
          echo "Version: ${SHORT_COMMIT_HASH}" >> $GITHUB_STEP_SUMMARY