name: Publish Stable

on:
  release:
    types:
      - published

jobs:
  portal:
    name: Publish to Maven Central
    runs-on: [self-hosted]
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      PROJECT_VERSION: ${{ github.event.release.tag_name }}
      PROJECT_CHANNEL: "stable"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Configure Git
        run: git config --global user.email "action@github.com" && git config --global user.name "Github Action"

      - name: Apply patches
        run: ./gradlew applyPatches --stacktrace

      - name: Publish to Sonatype Central Portal
        run: |
          ./gradlew :curepur-api:publishToCentralPortal --stacktrace